### PR TITLE
add `findCauseByName` documentation

### PR DESCRIPTION
**Pull request by DonutEspresso**
Sorry for the extra noise in the PR, looks I've got a plugin that strips whitespace. Happy to add the whitespace back in if it's a problem. 

I also noticed in the contribution guidelines that cr.joyent.us is preferred over github PRs - if that's still the case, let me know and I can refile.

### CODE REVIEW

**Comment by davepacheco** [comment]
This looks good.  Would you mind posting it to cr.joyent.us?  Let me know if you have any trouble with it.

**Comment by DonutEspresso** [comment]
OK, I think I migrated it over correctly - let me know if it needs any other touchups:
https://cr.joyent.us/#/c/325/

**Comment by davepacheco** [comment]
I just edited the commit message to match our convention.  If you're cool with it, I'll integrate the change.

**Comment by DonutEspresso** [comment]
Works for me. Thanks!

**Comment by davepacheco** [comment]
Integrated.  Thanks for doing this!

**Pull request closed without merging**
