### PR TITLE
Typescript: added first basic version of types

### PR DESCRIPTION
**Pull request by maghis**
The types in DefinitelyTyped are outdated. @davepacheco let me know if you are ok with adding TS types to the package.

### CODE REVIEW

**Comment by maghis** [comment]
@davepacheco @trentm feedback?

**Comment by davepacheco** [comment]
It's a nice idea, but I'm afraid we really can't commit to keeping these up to date.

**Comment by maghis** [comment]
@davepacheco np, moving them to https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by pasieronen** [comment]
@maghis it would be nice if the type definitions supported `import {WError} from "verror"` style imports, too.

**Pull request closed without merging**
